steps:
  - name: node:10 # Installing dependencies
    entrypoint: yarn
    args: ['install']
  - name: node:10 # Running build
    entrypoint: yarn
    args: ['build']
  - name: node:10 # Creating local .env file
    entrypoint: yarn
    args: ['create-env']
    env:
      - '_DB_URL=${_DB_URL}'
      - '_EMAIL_HOST=${_EMAIL_HOST}'
      - '_EMAIL_PORT=${_EMAIL_PORT}'
      - '_EMAIL_USER=${_EMAIL_USER}'
      - '_EMAIL_PASSWORD=${_EMAIL_PASSWORD}'
  - name: 'gcr.io/cloud-builders/gcloud' # deploying the app
    args: ['app', 'deploy']
timeout: '1600s'
