steps:
  - name: node:14 # Installing dependencies
    # entrypoint: npm
    args: ['npm', 'run', 'setup']
  - name: node:14 # Creating local .env file
    entrypoint: npm
    args: ['run', 'create-env']
    env:
      - 'DB_URL=${_DB_URL}'
      - 'EMAIL_HOST=${_EMAIL_HOST}'
      - 'EMAIL_PORT=${_EMAIL_PORT}'
      - 'EMAIL_USER=${_EMAIL_USER}'
      - 'EMAIL_PASSWORD=${_EMAIL_PASSWORD}'
  - name: 'gcr.io/cloud-builders/gcloud' # deploying the app
    args: ['app', 'deploy']
timeout: '1600s'
